apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chatsocket-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatsocket-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
